plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven {
        name = "Valkyrien Skies Internal"
        url = 'https://maven.valkyrienskies.org'
    }
    // Lower priority than VS repo on purpose
    maven {
        name = 'Forge'
        url = 'https://maven.minecraftforge.net/'
    }
}

dependencies {

    // Fails to import unless VS maven is commented out
    implementation("net.minecraftforge:mergetool:1.1.7")

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}